### ISSUE TITLE
Missing FAMC tag for individual / Missing FAMS tag for individual

### ISSUE THREAD

**Issue by coret** [nigel-parker/gedinline#16]
I have recently updated to the last version of gedinline on [Genealogy Online](https://www.genealogieonline.nl/en/) and my users are reporting they receive more warnings about their GEDCOM files (most cases version 5.5.1).
Warning that stand out the most are:

- Missing FAMC tag for individual  @Ixxx@
- Missing FAMS tag for individual  @Ixxx@

Are these warnings new in 3.1?
Where in the GEDCOM spec do you read FAMC and FAMS are required, is see {0:M}?

**Comment by nigel-parker** [comment]
The new checks have been in place since V3.0.5. The change was made as a result of issue #14. 

As I commented in that issue, previous to V7.0 it wasn't entirely clear that FAMC/FAMS should be mandatory in cases where the individual is referenced as a child or spouse in a family. The {0:M} marking is not relevant to the argument here, because obviously a FAMC pointer must be omitted if the individual is not mentioned as a child in any family. 

However to quote the 5.5.1 spec _‹‹The normal lineage links are shown through the use of pointers from the individual to the family through either the FAMC tag or the FAMS tag.››_ And later in the same paragraph, the FAMC pointer _‹‹is required to show any child to parent linkage for pedigree navigation.››_ Although the spec could have chosen to be more specific, it seems clear that the intention is that the pointers shall be present.

The V7.0 spec is  unambiguous, see the section dealing with FAMILY_RECORD.

**Comment by coret** [comment]
Thanks for the clarification!
