### ISSUE TITLE
Date years with 3 digits and leading space

### ISSUE THREAD

**Issue by jl5000** [nigel-parker/gedinline#18]
I'm running a 5.5.5 file through the validator and the validator isn't flagging invalid date lines such as:

2 DATE  936

A leading space before the year shouldn't be allowed.

**Comment by nigel-parker** [comment]
I think this line is valid. I read the space before 936 being the separator after the tag and not part of the value (see page 32 of the spec).

**Comment by jl5000** [comment]
Sorry, I should have been clearer as Github doesn't show it properly:

2 <SPACE> DATE <SPACE> <SPACE> 936

First space is the space after the tag, second space is the one I'm saying is illegal.

**Comment by nigel-parker** [comment]
Oh yes, I see! 

I must admit I find the 5.5.5 spec not to be easy to interpret in many cases. For an example relevant to your question, see page 41 where it states that "Line values _should not_ but _may_ contain leading white space." I presume that is why I don't give a warning in your case.

But please note that GED-inline's coverage of the 5.5.5 spec is incomplete, which is why I don't advertise it. I think  that  [GEDCOM 7.0](https://gedcom.io/specs/) is now more likely to be the standard of the future.

**Comment by jl5000** [comment]
Yes, I see that 7.0 seems to be gaining traction now with it's own Github repo so it's probably time for me to think about updating.
